Controllers/LeaveAllocationsController.cs
using AutoMapper;
using Leave_Management.Contracts;
using Leave_Management.Data;
using Leave_Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Leave_Management.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class LeaveAllocationsController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly UserManager<Employee> _userManager;
        private readonly IMapper _mapper;

        public LeaveAllocationsController(IUnitOfWork uow, UserManager<Employee> userManager, IMapper mapper)
        {
            _uow = uow;
            _userManager = userManager;
            _mapper = mapper;
        }
        // GET: LeaveAllocation
        public IActionResult Index()
        {
            var leaveType = _uow.LeaveType.GetAll().ToList();
            var mappsLeaveTypeVms = _mapper.Map<List<LeaveType>, List<LeaveTypeVM>>(leaveType);
            var model = new CreateLeaveAllocationVM
            {
                NumberUpdated = 0,
                LeaveTypes = mappsLeaveTypeVms
            };
            return View(model);
        }
        #region API Calls

        public IActionResult GetAll()
        {
            var employees = _userManager.GetUsersInRoleAsync("Employee").Result;
            var model = _mapper.Map<List<EmployeeVm>>(employees);
            return Json(new { data = model });
        }
        // GET: LeaveType/Delete/5
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var leaveType = await _uow.LeaveType.Get(id);
            if (leaveType == null)
                return Json(new { success = false, message = "Data Not Found!" });
            _uow.LeaveType.Delete(leaveType);
            _uow.Save();
            return Json(new { success = true, message = "Delete Operation Successfully" });
        }
        #endregion

        // GET: LeaveAllocation/Details/5
        public IActionResult Details(string id)
        {
            var employees = _mapper.Map<EmployeeVm>(_userManager.FindByIdAsync(id).Result);
            var allocations =
                _mapper.Map<List<LeaveAllocationVm>>(_uow.LeaveAllocation.GetAll(includeProperties: "LeaveType").Where(x => x.EmployeeId == id && x.Period == DateTime.Now.Year)
                    .ToList());
            var model = new ViewLeaveAllocationVM
            {
                Employee = employees,
                LeaveAllocationVms = allocations
            };

            return View(model);
        }

        // GET: LeaveAllocation/Create
        public async Task<ActionResult> SetLeave(int id)
        {
            var leaveTypes = await _uow.LeaveType.Get(id);
            var employees = _userManager.GetUsersInRoleAsync("Employee").Result;
            foreach (var emp in employees)
            {
                if (_uow.LeaveAllocation.CheckAllocation(id, emp.Id))
                    continue;
                var allocation = new LeaveAllocationVm
                {
                    DateCreated = DateTime.Now,
                    EmployeeId = emp.Id,
                    LeaveTypeId = id,
                    NumberOfDays = leaveTypes.DefaultDays,
                    Period = DateTime.Now.Year
                };
                var leaveAllocation = _mapper.Map<LeaveAllocation>(allocation);
                _uow.LeaveAllocation.Create(leaveAllocation);
                _uow.Save();
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult ListEmployee()
        {
            return View();
        }
        public async Task<ActionResult> Edit(int id)
        {
            var leaveAllocation = await _uow.LeaveAllocation
                .GetAllWithTwoEntity((x => x.Id == id), includeProperties: "LeaveType", includeProperty: "Employee");
            var model = _mapper.Map<EditLeaveAllocationVM>(leaveAllocation);
            return View(model);
        }

        // POST: LeaveAllocation/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditLeaveAllocationVM modeEditLeaveAllocationVm)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(modeEditLeaveAllocationVm);
                }

                var record = await _uow.LeaveAllocation.Get(id);
                record.NumberOfDays = modeEditLeaveAllocationVm.NumberOfDays;
                _uow.LeaveAllocation.Update(record);
                _uow.Save();

                return RedirectToAction(nameof(Details), new { id = modeEditLeaveAllocationVm.EmployeeId });
            }
            catch
            {
                return View();
            }
        }

    }
}

Controllers/LeaveRequestsController.cs
using AutoMapper;
using Leave_Management.Contracts;
using Leave_Management.Data;
using Leave_Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Leave_Management.Controllers
{
    [Authorize]
    public class LeaveRequestsController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly UserManager<Employee> _userManager;
        private readonly IMapper _mapper;

        public LeaveRequestsController(IUnitOfWork uow, UserManager<Employee> userManager, IMapper mapper)
        {
            _uow = uow;
            _userManager = userManager;
            _mapper = mapper;
        }

        // GET: LeaveRequests
        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            var leaveRequest = _uow.LeaveRequest.GetAll(includeProperties: "LeaveType",
                includeProperty: "RequestingEmployee", includeProperte: "ApprovedBy");
            var leaveRequestModel = _mapper.Map<List<LeaveRequestVm>>(leaveRequest);
            var model = new AdminLeaveRequestVm
            {
                TotalRequest = leaveRequestModel.Count,
                ApprovedRequest = leaveRequestModel.Count(x => x.Approved == true),
                PendingRequest = leaveRequestModel.Count(x => x.Approved == null),
                RejectedRequest = leaveRequestModel.Count(x => x.Approved == false),
                LeaveRequest = leaveRequestModel
            };
            return View(model);
        }
        public async Task<ActionResult> Details(int id)
        {
            var leaveRequest = await _uow.LeaveRequest.GetAllWithThreeEntity((x => x.Id == id), includeProperties: "ApprovedBy", includeProperty: "RequestingEmployee", includeProperte: "LeaveType");
            var model = _mapper.Map<LeaveRequestVm>(leaveRequest);
            return View(model);
        }


        public async Task<ActionResult> ApproveRequest(int id)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var leaveRequest = await _uow.LeaveRequest.Get(id);
                var employeeId = leaveRequest.RequestingEmployeeId;
                var leaveTypeId = leaveRequest.LeaveTypeId;
                var allocation = await _uow.LeaveAllocation.GetAllWithTwoEntity((x =>
                    x.EmployeeId == employeeId && x.Period == DateTime.Now.Year &&
                    x.LeaveType.Id == leaveTypeId));
                int daysRequested = (int)(leaveRequest.EndDate - leaveRequest.StartDate).TotalDays;
                //allocation.NumberOfDays -= daysRequested;
                allocation.NumberOfDays = allocation.NumberOfDays - daysRequested;

                leaveRequest.Approved = true;
                leaveRequest.ApprovedById = user.Id;
                leaveRequest.DateActioned = DateTime.Now;

                _uow.LeaveRequest.Update(leaveRequest);
                _uow.LeaveAllocation.Update(allocation);
                _uow.Save();
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<ActionResult> RejectRequest(int id)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var leaveRequest = await _uow.LeaveRequest.Get(id);
                leaveRequest.Approved = false;
                leaveRequest.ApprovedById = user.Id;
                leaveRequest.DateActioned = DateTime.Now;

                _uow.LeaveRequest.Update(leaveRequest);
                _uow.Save();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Index));
            }
        }


        public ActionResult MyLeave()
        {
            var employee = _userManager.GetUserAsync(User).Result;
            var employeeId = employee.Id;
            var employeeAllocation = _uow.LeaveAllocation.GetAll(includeProperties: "LeaveType")
                .Where(x => x.EmployeeId == employeeId && x.Period == DateTime.Now.Year)
                .ToList();
            var employeeRequest = _uow.LeaveRequest.GetAll((x => x.RequestingEmployeeId == employeeId),
                includeProperties: "LeaveType", includeProperty: "RequestingEmployee", includeProperte: "ApprovedBy");
            var employeeAllocationModel = _mapper.Map<List<LeaveAllocationVm>>(employeeAllocation);
            var employeeRequestModel = _mapper.Map<List<LeaveRequestVm>>(employeeRequest);

            var model = new EmployeeLeaveRequestVm
            {
                LeaveAllocations = employeeAllocationModel,
                LeaveRequests = employeeRequestModel
            };

            return View(model);
        }

        public async Task<IActionResult> CancelRequest(int id)
        {
            var leaveRequest = await _uow.LeaveRequest.Get(id);
            leaveRequest.Cancelled = true;
            _uow.LeaveRequest.Update(leaveRequest);
            _uow.Save();
            return RedirectToAction("MyLeave");
        }

        // GET: LeaveRequests/Upsert
        public IActionResult Upsert()
        {
            var leavetypes = _uow.LeaveType.GetAll();
            var leavetypesItem = leavetypes.Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString()
            });
            var model = new CreateLeaveRequestVm
            {
                LeaveTypes = leavetypesItem
            };
            return View(model);
        }

        // POST: LeaveRequests/Upsert
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(CreateLeaveRequestVm collection)
        {
            try
            {
                var startDate = Convert.ToDateTime(collection.StartDate);
                var endDate = Convert.ToDateTime(collection.EndDate);
                var employee = await _userManager.GetUserAsync(User);

                var allocation = await _uow.LeaveAllocation.GetAllWithTwoEntity((x =>
                    x.EmployeeId == employee.Id && x.Period == DateTime.Now.Year &&
                    x.LeaveType.Id == collection.LeaveTypeId));

                int dayRequested = (int)(endDate - startDate).TotalDays;

                var leaveTypes = _uow.LeaveType.GetAll();
                var leaveTypesItem = leaveTypes.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
                collection.LeaveTypes = leaveTypesItem;

                if (allocation == null)
                {
                    ModelState.AddModelError("", "You Have No Days Left");
                }
                if (DateTime.Compare(startDate, endDate) > 1)
                {
                    ModelState.AddModelError("", "Start Date cannot be further in the future than the End Date");
                }
                if (dayRequested > allocation.NumberOfDays)
                {
                    ModelState.AddModelError("", "You Do Not Sufficient Days For This Request");
                }
                if (!ModelState.IsValid)
                {
                    return View(collection);
                }

                var leaveRequestVm = new LeaveRequestVm
                {
                    RequestingEmployeeId = employee.Id,
                    StartDate = startDate,
                    EndDate = endDate,
                    Approved = null,
                    DateRequested = DateTime.Now,
                    DateActioned = DateTime.Now,
                    LeaveTypeId = collection.LeaveTypeId,
                    RequestComments = collection.RequestComments
                };

                var leaveRequest = _mapper.Map<LeaveRequest>(leaveRequestVm);
                _uow.LeaveRequest.Create(leaveRequest);
                _uow.Save();
                return RedirectToAction(nameof(MyLeave));
            }
            catch (Exception)
            {
                return View(collection);
            }
        }

        public IActionResult GetAll()
        {
            var leaveRequest = _uow.LeaveRequest.GetAll(includeProperties: "LeaveType",
                includeProperty: "RequestingEmployee", includeProperte: "ApprovedBy");
            var leaveRequestModel = _mapper.Map<List<LeaveRequestVm>>(leaveRequest);
            var model = new AdminLeaveRequestVm
            {
                TotalRequest = leaveRequestModel.Count,
                ApprovedRequest = leaveRequestModel.Count(x => x.Approved == true),
                PendingRequest = leaveRequestModel.Count(x => x.Approved == null),
                RejectedRequest = leaveRequestModel.Count(x => x.Approved == false),
                LeaveRequest = leaveRequestModel
            };
            return Json(new { data = model });
        }
    }
}

Controllers/LeaveTypesController.cs
using AutoMapper;
using Leave_Management.Contracts;
using Leave_Management.Data;
using Leave_Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Leave_Management.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class LeaveTypesController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly IMapper _mapper;

        public LeaveTypesController(IUnitOfWork uow, IMapper mapper)
        {
            _uow = uow;
            _mapper = mapper;
        }

        #region API Calls

        public IActionResult GetAll()
        {
            var leaveType = _uow.LeaveType.GetAll().ToList();
            var model = _mapper.Map<List<LeaveType>, List<LeaveTypeVM>>(leaveType);
            return Json(new { data = model });
        }

        // GET: LeaveType/Delete/5
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var dataLeaveType = await _uow.LeaveType.Get(id);
            if (dataLeaveType == null)
                return Json(new { success = false, message = "Data Not Found!" });
            _uow.LeaveType.Delete(dataLeaveType);
            _uow.Save();
            return Json(new { success = true, message = "Delete Operation Successfully" });
        }
        #endregion

        // GET: LeaveType
        public ActionResult Index()
        {
            return View();
        }

        // GET: LeaveType/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var model = await _uow.LeaveType.GetFirstOrDefault(u => u.Id == id);
            if (model == null)
            {
                return NotFound();
            }

            var models = _mapper.Map<LeaveTypeVM>(model);

            return View(models);
        }

        // GET: LeaveType
        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
            {
                //Create
                return View(new LeaveTypeVM());
            }
            //Update

            var model = await _uow.LeaveType.GetFirstOrDefault(u => u.Id == id);
            var leaveTypeVm = _mapper.Map<LeaveTypeVM>(model);

            if (leaveTypeVm == null)
            {
                return NotFound();
            }
            return View(leaveTypeVm);
        }

        // POST: LeaveType/Create/Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(LeaveTypeVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                if (model.Id == 0) //Create
                {
                    TempData["result"] = "Create";
                    var leaveType = _mapper.Map<LeaveType>(model);
                    leaveType.DateCreated = DateTime.Now;
                    _uow.LeaveType.Create(leaveType);
                }
                else // Update
                {
                    TempData["result"] = "Update";
                    var leaveType = _mapper.Map<LeaveType>(model);
                    _uow.LeaveType.Update(leaveType);
                }
                _uow.Save();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(model);
            }
        }
    }
}

Views/Shared/_AdminLTE.cshtml
@using Microsoft.AspNetCore.Identity
@using Leave_Management.Data
@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core Leave Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="~/css/jquery-ui.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/toastr.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/font-awesome.css" />


    <link rel="stylesheet" href="~/css/adminlte.min.css">
</head>

<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
                @*<li class="nav-item d-none d-sm-inline-block">
                        <a href="index3.html" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item d-none d-sm-inline-block">
                        <a href="#" class="nav-link">Contact</a>
                    </li>*@
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="#" class="brand-link">
                @*<img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                    style="opacity: .8">*@
                <span class="brand-text font-weight-light">Leave Management</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <partial name="_LoginPartial" />
                <hr />

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">
                                <i class="nav-icon fas fa-home"></i>
                                <p>
                                    Home
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="LeaveRequests" asp-action="Upsert" class="nav-link">
                                <i class="nav-icon fas fa-pen-alt"></i>
                                <p>
                                    Apply For Leave
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="LeaveRequests" asp-action="MyLeave" class="nav-link">
                                <i class="nav-icon fas fa-book-open"></i>
                                <p>
                                    My Leave
                                </p>
                            </a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item has-treeview menu-open">
                                    <a href="#" class="nav-link active">
                                        <i class="nav-icon fas fa-tachometer-alt"></i>
                                        <p>
                                            Manage
                                            <i class="right fas fa-angle-left"></i>
                                        </p>
                                    </a>
                                    <ul class="nav nav-treeview">
                                        <li class="nav-item">
                                            <a asp-controller="LeaveTypes" asp-action="Index" class="nav-link">
                                                <i class="fas fa-list nav-icon"></i>
                                                <p>Leave Types</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a asp-controller="LeaveAllocations" asp-action="Index" class="nav-link">
                                                <i class="fas fa-user-plus nav-icon"></i>
                                                <p>Leave Allocations</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a asp-controller="LeaveRequests" asp-action="Index" class="nav-link">
                                                <i class="fas fa-cogs nav-icon"></i>
                                                <p>Leave Requests</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a asp-controller="LeaveAllocations" asp-action="ListEmployee" class="nav-link">
                                                <i class="fas fa-users nav-icon"></i>
                                                <p>Employees</p>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            }
                        }
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">

                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                Styled by <a href="https://adminlte.io">AdminLTE.io</a>
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; @DateTime.Now.Year Core Leave Management System.</strong> All rights reserved.
        </footer>
    </div>    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/all.min.js"></script>
    <script src="~/js/dataTable.min.js"></script>
    <script src="~/js/toastr.min.js"></script>
    <script src="~/js/sweetalert.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.js"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>